import { TApiError } from './types'

export const SERVER_ERROR_CODE = 'SVE_500'

export const EMPTY_FILTERS_ERROR_CODE = 'EFT_404'

export const INVALID_CLIENT_ERROR_CODE = 'IVC_404'

export const MISSIN_TOKEN_ERROR_CODE = 'MTE_400'
export const INVALID_TOKEN_ERROR_CODE = 'ITE_401'

export const MISSIN_CREDENTIALS_ERROR_CODE = 'MCE_400'
export const INVALID_CREDENTIALS_ERROR_CODE = 'ICE_401'

export const INVALID_PHONE_ERROR_CODE = 'IPE_401'

export const FAILED_MSG_TEMPLATE_ERROR_CODE = 'FME_400'

export const FAILED_EMAIL_ERROR_CODE = 'FEE_400'

export const API_ERRORS_ARRAY: TApiError[] = [
    SERVER_ERROR_CODE,
    EMPTY_FILTERS_ERROR_CODE,
    MISSIN_CREDENTIALS_ERROR_CODE,
    MISSIN_TOKEN_ERROR_CODE,
    INVALID_CREDENTIALS_ERROR_CODE,
    INVALID_TOKEN_ERROR_CODE,
    INVALID_PHONE_ERROR_CODE,
    INVALID_CLIENT_ERROR_CODE,
    FAILED_MSG_TEMPLATE_ERROR_CODE,
    FAILED_EMAIL_ERROR_CODE,
]
