import {
    EMPTY_FILTERS_ERROR_CODE,
    INVALID_CLIENT_ERROR_CODE,
    INVALID_CREDENTIALS_ERROR_CODE,
    INVALID_TOKEN_ERROR_CODE,
    INVALID_PHONE_ERROR_CODE,
    MISSIN_TOKEN_ERROR_CODE,
    MISSIN_CREDENTIALS_ERROR_CODE,
    SERVER_ERROR_CODE,
    FAILED_MSG_TEMPLATE_ERROR_CODE,
    FAILED_EMAIL_ERROR_CODE,
} from './errors'

export type TApiError =
    | typeof SERVER_ERROR_CODE
    | typeof EMPTY_FILTERS_ERROR_CODE
    | typeof MISSIN_CREDENTIALS_ERROR_CODE
    | typeof MISSIN_TOKEN_ERROR_CODE
    | typeof INVALID_TOKEN_ERROR_CODE
    | typeof INVALID_PHONE_ERROR_CODE
    | typeof INVALID_CREDENTIALS_ERROR_CODE
    | typeof INVALID_CLIENT_ERROR_CODE
    | typeof FAILED_MSG_TEMPLATE_ERROR_CODE
    | typeof FAILED_EMAIL_ERROR_CODE
